#!/usr/bin/env groovy
import hudson.model.*
import hudson.EnvVars
import groovy.json.JsonSlurperClassic
import groovy.json.JsonBuilder
import groovy.json.JsonOutput
import java.net.URL

pipeline
{
agent 
{
node 'master'
}
tools 
{
maven 'Maven'
jdk   'Java-1.8'
}
stages
{
//stage ('Build')
//{
//steps
//{
//sh 'mvn clean install'
//}
//}
stage('Build & Push Docker Image')
{
steps
{
script 
{
withDockerRegistry(credentialsId: 'ECR', url: 'https://594952790969.dkr.ecr.us-east-2.amazonaws.com')
{
def customImage = docker.build("594952790969.dkr.ecr.us-east-2.amazonaws.com/test:${env.BUILD_NUMBER}")
customImage.push("${env.BUILD_NUMBER}")
}
}
}
}
stage('Deploy')
{
steps
{
script
{
sh "kubectl set image deployment.v1.apps/website website=594952790969.dkr.ecr.us-east-2.amazonaws.com/test:${env.BUILD_NUMBER}"
}
}
}
}
}
