#!/usr/bin/env groovy
import hudson.model.*
import hudson.EnvVars
import groovy.json.JsonSlurperClassic
import groovy.json.JsonBuilder
import groovy.json.JsonOutput
import java.net.URL

pipeline
{
agent 
{
node 'master'
}
tools 
{
maven 'Maven'
jdk   'Java-1.8'
}
stages
{
stage ('Build')
{
steps
{
sh 'mvn clean install'
}
}
}
}
